example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_html, show_json, show_xml

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_html, name='show_html'),
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('create-task/', create_task, name='create_task'),
    path('logout/', logout_user, name='logout'),
]   

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchlist(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.conf import settings

class Task(models.Model):
    # https://stackoverflow.com/questions/34305805/foreignkey-user-in-models
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from katalog.models import CatalogItem
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_katalog = CatalogItem.objects.all()
    context = {
        'catalog_items': data_katalog,
        'nama': 'Nadya Hoesin',
        'npm': '2106651673'
    }

    return render(request, "katalog.html", context)

mywatchlist/views.py
from mywatchlist.models import MyWatchlist
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers

# TODO: Create your views here.
def show_html(request):
    watchlist_data = MyWatchlist.objects.all()
    number_of_watched_films = len([film for film in watchlist_data if film.watched])
    banyak_menonton = number_of_watched_films >= len(watchlist_data) - number_of_watched_films
    context = {
        'watchlist': watchlist_data,
        'nama': 'Nadya Hoesin',
        'npm': '2106651673',
        'pesan': 'Selamat, kamu sudah banyak menonton!' if banyak_menonton else 'Wah, kamu masih sedikit menonton!'
    }

    return render(request, "mywatchlist.html", context)

def show_json(request):
    watchlist_data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", watchlist_data), content_type="application/json")

def show_xml(request):
    watchlist_data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", watchlist_data), content_type="application/xml")

todolist/views.py
from xxlimited import Null
from todolist.models import Task
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
import datetime

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    try:
        data_task = Task.objects.get(user=request.user)
    except:
        data_task = False

    context = {
        'tasks': data_task,
        'username': request.user.username
    }
    return render(request, "todolist.html", context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            # return redirect('wishlist:show_wishlist')
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form': form}
    return render(request, 'register.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    pass

def logout_user(request):
    logout(request)
    # return redirect('wishlist:login')
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in catalog_items %}
    <tr>
      <th>{{item.item_name}}</th>
      <th>{{item.item_price}}</th>
      <th>{{item.item_stock}}</th>
      <th>{{item.rating}}</th>
      <th>{{item.description}}</th>
      <th>{{item.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in watchlist %}
    <tr>
      <th>{{film.watched}}</th>
      <th>{{film.title}}</th>
      <th>{{film.rating}}</th>
      <th>{{film.release_date}}</th>
      <th>{{film.review}}</th>
    </tr>
    {% endfor %}
  </table>

  <p>{{pesan}}</p>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block content %}

<h1>Assignment 4 PBP/PBD</h1>

<h5>Username pengguna: </h5>
<p>{{username}}</p>

<table>
    <tr>
        <th>Tanggal Pembuatan</th>
        <th>Judul</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% if tasks %}
        {% for task in tasks %}
        <tr>
            <th>{{task.date}}</th>
            <th>{{task.title}}</th>
            <th>{{task.description}}</th>
        </tr>
        {% endfor %}
    {% endif %}
</table>

<button><a href="{% url 'todolist:create_task' %}">Buat task baru</a></button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<h1>Assignment 4 PBP/PBD</h1>

<h5>Username pengguna: </h5>
<p>{{username}}</p>

<table>
    <tr>
        <th>Tanggal Pembuatan</th>
        <th>Judul</th>
        <th>Deskripsi</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% if tasks %}
        {% for task in tasks %}
        <tr>
            <th>{{task.date}}</th>
            <th>{{task.title}}</th>
            <th>{{task.description}}</th>
        </tr>
        {% endfor %}
    {% endif %}
</table>

<button><a href="{% url 'todolist:create_task' %}">Buat task baru</a></button>
<button><a href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}